BOT_NAME = "ccaudio"

SPIDER_MODULES = ["ccaudio.download"]
NEWSPIDER_MODULE = "ccaudio.download"

ROBOTSTXT_OBEY = False

CONCURRENT_REQUESTS = 16
CONCURRENT_REQUESTS_PER_DOMAIN = 16

DOWNLOAD_DELAY = 0

DOWNLOAD_TIMEOUT = 300

DOWNLOAD_WARNSIZE = 500 * 1024 * 1024
DOWNLOAD_MAXSIZE = 1024 * 1024 * 1024

AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 0.5
AUTOTHROTTLE_MAX_DELAY = 60.0
AUTOTHROTTLE_TARGET_CONCURRENCY = 16.0
AUTOTHROTTLE_DEBUG = False

RETRY_ENABLED = True
RETRY_TIMES = 3
RETRY_HTTP_CODES = [500, 502, 503, 504, 408, 429]

ITEM_PIPELINES = {
    "ccaudio.download.scrapy_pipelines.AudioProcessingPipeline": 300,
}

LOG_LEVEL = "INFO"

REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
TWISTED_REACTOR = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"
FEED_EXPORT_ENCODING = "utf-8"

TELNETCONSOLE_ENABLED = False

HTTPCACHE_ENABLED = False

OUTPUT_DIR = "./output"
SHARD_SIZE = 100
